
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 13 18:00:17 CST 2013
//----------------------------------------------------

package compiladores;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Apr 13 18:00:17 CST 2013
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\127\000\002\002\004\000\002\002\005\000\002\003" +
    "\002\000\002\003\004\000\002\004\002\000\002\004\004" +
    "\000\002\005\006\000\002\007\003\000\002\007\005\000" +
    "\002\006\004\000\002\006\002\000\002\010\023\000\002" +
    "\011\010\000\002\012\004\000\002\012\004\000\002\012" +
    "\002\000\002\013\002\000\002\013\004\000\002\013\004" +
    "\000\002\013\004\000\002\014\005\000\002\017\011\000" +
    "\002\037\004\000\002\037\005\000\002\015\002\000\002" +
    "\015\004\000\002\016\003\000\002\016\004\000\002\020" +
    "\003\000\002\020\003\000\002\021\005\000\002\022\005" +
    "\000\002\022\002\000\002\023\003\000\002\023\002\000" +
    "\002\024\004\000\002\024\006\000\002\025\005\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\026\005\000\002\026\010\000\002\026\007" +
    "\000\002\026\013\000\002\026\011\000\002\026\007\000" +
    "\002\026\011\000\002\027\004\000\002\027\002\000\002" +
    "\036\005\000\002\036\002\000\002\030\003\000\002\030" +
    "\014\000\002\031\003\000\002\031\003\000\002\032\003" +
    "\000\002\032\005\000\002\032\006\000\002\032\005\000" +
    "\002\032\010\000\002\033\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\007\000\002\033\007\000\002\033\004\000\002\033\005" +
    "\000\002\033\003\000\002\034\003\000\002\034\005\000" +
    "\002\034\002\000\002\035\003\000\002\035\003\000\002" +
    "\035\003\000\002\035\003\000\002\035\003\000\002\035" +
    "\003\000\002\035\003\000\002\035\003\000\002\035\003" +
    "\000\002\035\003\000\002\035\003\000\002\035\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\274\000\006\036\uffff\037\uffff\001\002\000\004\002" +
    "\276\001\002\000\006\036\006\037\ufffd\001\002\000\004" +
    "\035\267\001\002\000\006\036\ufffe\037\ufffe\001\002\000" +
    "\004\037\012\001\002\000\004\037\ufffc\001\002\000\004" +
    "\035\014\001\002\000\004\002\000\001\002\000\010\024" +
    "\020\066\016\067\017\001\002\000\004\024\221\001\002" +
    "\000\004\035\220\001\002\000\004\035\217\001\002\000" +
    "\004\040\021\001\002\000\004\041\022\001\002\000\004" +
    "\042\023\001\002\000\004\043\024\001\002\000\004\064" +
    "\025\001\002\000\004\005\026\001\002\000\004\026\027" +
    "\001\002\000\004\027\030\001\002\000\004\035\031\001" +
    "\002\000\004\065\032\001\002\000\004\024\033\001\002" +
    "\000\016\024\041\035\034\046\043\050\042\051\037\055" +
    "\035\001\002\000\010\020\uffcd\026\176\031\uffc9\001\002" +
    "\000\004\031\160\001\002\000\004\031\152\001\002\000" +
    "\004\031\uffca\001\002\000\004\025\150\001\002\000\016" +
    "\024\041\035\034\046\043\050\042\051\037\055\035\001" +
    "\002\000\004\064\140\001\002\000\004\064\044\001\002" +
    "\000\032\004\047\005\062\021\061\033\045\034\063\035" +
    "\056\045\050\051\060\052\052\053\054\054\051\064\055" +
    "\001\002\000\046\006\uffc3\007\uffc3\010\uffc3\011\uffc3\012" +
    "\uffc3\013\uffc3\014\uffc3\015\uffc3\016\uffc3\017\uffc3\022\uffc3" +
    "\023\uffc3\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032\uffc3\065" +
    "\uffc3\001\002\000\046\006\uffc8\007\uffc8\010\uffc8\011\uffc8" +
    "\012\uffc8\013\uffc8\014\uffc8\015\uffc8\016\uffc8\017\uffc8\022" +
    "\uffc8\023\uffc8\026\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8" +
    "\065\uffc8\001\002\000\050\006\uffda\007\uffda\010\uffda\011" +
    "\uffda\012\uffda\013\uffda\014\uffda\015\uffda\016\uffda\017\uffda" +
    "\022\uffda\023\uffda\026\136\027\uffda\030\uffda\031\uffda\032" +
    "\uffda\035\uffda\065\uffda\001\002\000\050\006\uffdb\007\uffdb" +
    "\010\uffdb\011\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb\016" +
    "\uffdb\017\uffdb\022\uffdb\023\uffdb\026\uffdb\027\uffdb\030\uffdb" +
    "\031\uffdb\032\uffdb\035\uffdb\065\uffdb\001\002\000\006\004" +
    "\126\035\127\001\002\000\046\006\uffc2\007\uffc2\010\uffc2" +
    "\011\uffc2\012\uffc2\013\uffc2\014\uffc2\015\uffc2\016\uffc2\017" +
    "\uffc2\022\uffc2\023\uffc2\026\uffc2\027\uffc2\030\uffc2\031\uffc2" +
    "\032\uffc2\065\uffc2\001\002\000\040\006\067\007\101\010" +
    "\072\011\100\012\074\013\071\014\073\015\077\016\103" +
    "\017\070\022\102\023\065\026\075\031\066\065\121\001" +
    "\002\000\046\006\uffc1\007\uffc1\010\uffc1\011\uffc1\012\uffc1" +
    "\013\uffc1\014\uffc1\015\uffc1\016\uffc1\017\uffc1\022\uffc1\023" +
    "\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\065\uffc1" +
    "\001\002\000\032\004\047\005\062\021\061\033\045\034" +
    "\063\035\056\045\050\051\060\052\052\053\054\054\051" +
    "\064\055\001\002\000\050\006\uffd8\007\uffd8\010\uffd8\011" +
    "\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016\uffd8\017\uffd8" +
    "\022\uffd8\023\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\032" +
    "\uffd8\035\uffd8\065\uffd8\001\002\000\046\006\uffbf\007\uffbf" +
    "\010\uffbf\011\uffbf\012\uffbf\013\uffbf\014\uffbf\015\uffbf\016" +
    "\uffbf\017\uffbf\022\uffbf\023\uffbf\026\uffbf\027\uffbf\030\uffbf" +
    "\031\uffbf\032\uffbf\065\uffbf\001\002\000\046\006\uffc0\007" +
    "\uffc0\010\uffc0\011\uffc0\012\uffc0\013\uffc0\014\uffc0\015\uffc0" +
    "\016\uffc0\017\uffc0\022\uffc0\023\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\065\uffc0\001\002\000\032\004\047" +
    "\005\062\021\061\033\045\034\063\035\056\045\050\051" +
    "\060\052\052\053\054\054\051\064\055\001\002\000\050" +
    "\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9\013\uffd9\014" +
    "\uffd9\015\uffd9\016\uffd9\017\uffd9\022\uffd9\023\uffd9\026\uffd9" +
    "\027\uffd9\030\uffd9\031\uffd9\032\uffd9\035\uffd9\065\uffd9\001" +
    "\002\000\046\006\uffba\007\uffba\010\uffba\011\uffba\012\uffba" +
    "\013\uffba\014\uffba\015\uffba\016\uffba\017\uffba\022\uffba\023" +
    "\uffba\026\uffba\027\uffba\030\uffba\031\uffba\032\uffba\065\uffba" +
    "\001\002\000\046\006\067\007\101\010\072\011\100\012" +
    "\074\013\071\014\073\015\077\016\103\017\070\022\102" +
    "\023\065\026\075\027\uffbc\030\uffbc\031\066\032\uffbc\065" +
    "\uffbc\001\002\000\032\004\uffab\005\uffab\021\uffab\033\uffab" +
    "\034\uffab\035\uffab\045\uffab\051\uffab\052\uffab\053\uffab\054" +
    "\uffab\064\uffab\001\002\000\006\035\107\060\110\001\002" +
    "\000\032\004\uffb6\005\uffb6\021\uffb6\033\uffb6\034\uffb6\035" +
    "\uffb6\045\uffb6\051\uffb6\052\uffb6\053\uffb6\054\uffb6\064\uffb6" +
    "\001\002\000\032\004\uffad\005\uffad\021\uffad\033\uffad\034" +
    "\uffad\035\uffad\045\uffad\051\uffad\052\uffad\053\uffad\054\uffad" +
    "\064\uffad\001\002\000\032\004\uffb1\005\uffb1\021\uffb1\033" +
    "\uffb1\034\uffb1\035\uffb1\045\uffb1\051\uffb1\052\uffb1\053\uffb1" +
    "\054\uffb1\064\uffb1\001\002\000\032\004\uffb4\005\uffb4\021" +
    "\uffb4\033\uffb4\034\uffb4\035\uffb4\045\uffb4\051\uffb4\052\uffb4" +
    "\053\uffb4\054\uffb4\064\uffb4\001\002\000\032\004\uffb0\005" +
    "\uffb0\021\uffb0\033\uffb0\034\uffb0\035\uffb0\045\uffb0\051\uffb0" +
    "\052\uffb0\053\uffb0\054\uffb0\064\uffb0\001\002\000\032\004" +
    "\uffb2\005\uffb2\021\uffb2\033\uffb2\034\uffb2\035\uffb2\045\uffb2" +
    "\051\uffb2\052\uffb2\053\uffb2\054\uffb2\064\uffb2\001\002\000" +
    "\032\004\047\005\062\021\061\033\045\034\063\035\056" +
    "\045\050\051\060\052\052\053\054\054\051\064\055\001" +
    "\002\000\032\004\047\005\062\021\061\033\045\034\063" +
    "\035\056\045\050\051\060\052\052\053\054\054\051\064" +
    "\055\001\002\000\032\004\uffaf\005\uffaf\021\uffaf\033\uffaf" +
    "\034\uffaf\035\uffaf\045\uffaf\051\uffaf\052\uffaf\053\uffaf\054" +
    "\uffaf\064\uffaf\001\002\000\032\004\uffb3\005\uffb3\021\uffb3" +
    "\033\uffb3\034\uffb3\035\uffb3\045\uffb3\051\uffb3\052\uffb3\053" +
    "\uffb3\054\uffb3\064\uffb3\001\002\000\032\004\uffb5\005\uffb5" +
    "\021\uffb5\033\uffb5\034\uffb5\035\uffb5\045\uffb5\051\uffb5\052" +
    "\uffb5\053\uffb5\054\uffb5\064\uffb5\001\002\000\032\004\uffac" +
    "\005\uffac\021\uffac\033\uffac\034\uffac\035\uffac\045\uffac\051" +
    "\uffac\052\uffac\053\uffac\054\uffac\064\uffac\001\002\000\032" +
    "\004\uffae\005\uffae\021\uffae\033\uffae\034\uffae\035\uffae\045" +
    "\uffae\051\uffae\052\uffae\053\uffae\054\uffae\064\uffae\001\002" +
    "\000\046\006\067\007\101\010\072\011\100\012\074\013" +
    "\071\014\073\015\077\016\103\017\070\022\102\023\065" +
    "\026\075\027\uffc7\030\uffc7\031\066\032\uffc7\065\uffc7\001" +
    "\002\000\040\006\067\007\101\010\072\011\100\012\074" +
    "\013\071\014\073\015\077\016\103\017\070\022\102\023" +
    "\065\026\075\027\106\031\066\001\002\000\046\006\uffc6" +
    "\007\uffc6\010\uffc6\011\uffc6\012\uffc6\013\uffc6\014\uffc6\015" +
    "\uffc6\016\uffc6\017\uffc6\022\uffc6\023\uffc6\026\uffc6\027\uffc6" +
    "\030\uffc6\031\uffc6\032\uffc6\065\uffc6\001\002\000\004\064" +
    "\111\001\002\000\046\006\uffc5\007\uffc5\010\uffc5\011\uffc5" +
    "\012\uffc5\013\uffc5\014\uffc5\015\uffc5\016\uffc5\017\uffc5\022" +
    "\uffc5\023\uffc5\026\uffc5\027\uffc5\030\uffc5\031\uffc5\032\uffc5" +
    "\065\uffc5\001\002\000\036\004\047\005\062\021\061\032" +
    "\uffb7\033\045\034\063\035\056\045\050\051\060\052\052" +
    "\053\054\054\051\064\055\065\uffb7\001\002\000\042\006" +
    "\067\007\101\010\072\011\100\012\074\013\071\014\073" +
    "\015\077\016\103\017\070\022\102\023\065\026\075\031" +
    "\066\032\uffb9\065\uffb9\001\002\000\006\032\114\065\115" +
    "\001\002\000\032\004\047\005\062\021\061\033\045\034" +
    "\063\035\056\045\050\051\060\052\052\053\054\054\051" +
    "\064\055\001\002\000\046\006\uffc4\007\uffc4\010\uffc4\011" +
    "\uffc4\012\uffc4\013\uffc4\014\uffc4\015\uffc4\016\uffc4\017\uffc4" +
    "\022\uffc4\023\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032" +
    "\uffc4\065\uffc4\001\002\000\042\006\067\007\101\010\072" +
    "\011\100\012\074\013\071\014\073\015\077\016\103\017" +
    "\070\022\102\023\065\026\075\031\066\032\uffb8\065\uffb8" +
    "\001\002\000\040\006\067\007\101\010\072\011\100\012" +
    "\074\013\071\014\073\015\077\016\103\017\070\022\102" +
    "\023\065\026\075\031\066\065\120\001\002\000\046\006" +
    "\uffbb\007\uffbb\010\uffbb\011\uffbb\012\uffbb\013\uffbb\014\uffbb" +
    "\015\uffbb\016\uffbb\017\uffbb\022\uffbb\023\uffbb\026\uffbb\027" +
    "\uffbb\030\uffbb\031\uffbb\032\uffbb\065\uffbb\001\002\000\016" +
    "\024\041\035\034\046\043\050\042\051\037\055\035\001" +
    "\002\000\024\024\uffcf\025\uffcf\035\uffcf\044\uffcf\046\uffcf" +
    "\047\123\050\uffcf\051\uffcf\055\uffcf\001\002\000\016\024" +
    "\041\035\034\046\043\050\042\051\037\055\035\001\002" +
    "\000\024\024\uffd6\025\uffd6\035\uffd6\044\uffd6\046\uffd6\047" +
    "\uffd6\050\uffd6\051\uffd6\055\uffd6\001\002\000\024\024\uffd0" +
    "\025\uffd0\035\uffd0\044\uffd0\046\uffd0\047\uffd0\050\uffd0\051" +
    "\uffd0\055\uffd0\001\002\000\004\026\133\001\002\000\004" +
    "\064\130\001\002\000\036\004\047\005\062\021\061\032" +
    "\uffb7\033\045\034\063\035\056\045\050\051\060\052\052" +
    "\053\054\054\051\064\055\065\uffb7\001\002\000\006\032" +
    "\114\065\132\001\002\000\046\006\uffbd\007\uffbd\010\uffbd" +
    "\011\uffbd\012\uffbd\013\uffbd\014\uffbd\015\uffbd\016\uffbd\017" +
    "\uffbd\022\uffbd\023\uffbd\026\uffbd\027\uffbd\030\uffbd\031\uffbd" +
    "\032\uffbd\065\uffbd\001\002\000\032\004\047\005\062\021" +
    "\061\033\045\034\063\035\056\045\050\051\060\052\052" +
    "\053\054\054\051\064\055\001\002\000\040\006\067\007" +
    "\101\010\072\011\100\012\074\013\071\014\073\015\077" +
    "\016\103\017\070\022\102\023\065\026\075\027\135\031" +
    "\066\001\002\000\046\006\uffbe\007\uffbe\010\uffbe\011\uffbe" +
    "\012\uffbe\013\uffbe\014\uffbe\015\uffbe\016\uffbe\017\uffbe\022" +
    "\uffbe\023\uffbe\026\uffbe\027\uffbe\030\uffbe\031\uffbe\032\uffbe" +
    "\065\uffbe\001\002\000\004\027\137\001\002\000\050\006" +
    "\uffdc\007\uffdc\010\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc" +
    "\015\uffdc\016\uffdc\017\uffdc\022\uffdc\023\uffdc\026\uffdc\027" +
    "\uffdc\030\uffdc\031\uffdc\032\uffdc\035\uffdc\065\uffdc\001\002" +
    "\000\032\004\047\005\062\021\061\033\045\034\063\035" +
    "\056\045\050\051\060\052\052\053\054\054\051\064\055" +
    "\001\002\000\040\006\067\007\101\010\072\011\100\012" +
    "\074\013\071\014\073\015\077\016\103\017\070\022\102" +
    "\023\065\026\075\031\066\065\142\001\002\000\016\024" +
    "\041\035\034\046\043\050\042\051\037\055\035\001\002" +
    "\000\024\024\uffd5\025\uffd5\035\uffd5\044\uffd5\046\uffd5\047" +
    "\uffd5\050\uffd5\051\uffd5\055\uffd5\001\002\000\020\024\041" +
    "\025\146\035\034\046\043\050\042\051\037\055\035\001" +
    "\002\000\022\024\uffe7\025\uffe7\035\uffe7\044\uffe7\046\uffe7" +
    "\050\uffe7\051\uffe7\055\uffe7\001\002\000\024\024\uffd7\025" +
    "\uffd7\035\uffd7\044\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7" +
    "\055\uffd7\001\002\000\022\024\uffe6\025\uffe6\035\uffe6\044" +
    "\uffe6\046\uffe6\050\uffe6\051\uffe6\055\uffe6\001\002\000\004" +
    "\025\151\001\002\000\004\002\ufff6\001\002\000\004\035" +
    "\153\001\002\000\004\064\154\001\002\000\036\004\047" +
    "\005\062\021\061\032\uffb7\033\045\034\063\035\056\045" +
    "\050\051\060\052\052\053\054\054\051\064\055\065\uffb7" +
    "\001\002\000\006\032\114\065\156\001\002\000\004\030" +
    "\157\001\002\000\024\024\uffd1\025\uffd1\035\uffd1\044\uffd1" +
    "\046\uffd1\047\uffd1\050\uffd1\051\uffd1\055\uffd1\001\002\000" +
    "\006\056\161\061\162\001\002\000\004\031\167\001\002" +
    "\000\004\064\163\001\002\000\004\033\164\001\002\000" +
    "\004\065\165\001\002\000\004\030\166\001\002\000\024" +
    "\024\uffd3\025\uffd3\035\uffd3\044\uffd3\046\uffd3\047\uffd3\050" +
    "\uffd3\051\uffd3\055\uffd3\001\002\000\004\057\170\001\002" +
    "\000\004\064\171\001\002\000\032\004\047\005\062\021" +
    "\061\033\045\034\063\035\056\045\050\051\060\052\052" +
    "\053\054\054\051\064\055\001\002\000\040\006\067\007" +
    "\101\010\072\011\100\012\074\013\071\014\073\015\077" +
    "\016\103\017\070\022\102\023\065\026\075\031\066\065" +
    "\173\001\002\000\004\030\174\001\002\000\024\024\uffd4" +
    "\025\uffd4\035\uffd4\044\uffd4\046\uffd4\047\uffd4\050\uffd4\051" +
    "\uffd4\055\uffd4\001\002\000\004\020\201\001\002\000\032" +
    "\004\047\005\062\021\061\033\045\034\063\035\056\045" +
    "\050\051\060\052\052\053\054\054\051\064\055\001\002" +
    "\000\040\006\067\007\101\010\072\011\100\012\074\013" +
    "\071\014\073\015\077\016\103\017\070\022\102\023\065" +
    "\026\075\027\200\031\066\001\002\000\004\020\uffce\001" +
    "\002\000\032\004\047\005\062\021\061\033\045\034\063" +
    "\035\056\045\050\051\060\052\052\053\054\054\051\064" +
    "\203\001\002\000\040\006\067\007\101\010\072\011\100" +
    "\012\074\013\071\014\073\015\077\016\103\017\070\022" +
    "\102\023\065\026\075\030\uffcc\031\066\001\002\000\032" +
    "\004\047\005\062\021\061\033\045\034\063\035\056\045" +
    "\050\051\060\052\052\053\054\054\051\064\055\001\002" +
    "\000\004\030\205\001\002\000\024\024\uffd2\025\uffd2\035" +
    "\uffd2\044\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2\055\uffd2" +
    "\001\002\000\040\006\uffbf\007\uffbf\010\uffbf\011\uffbf\012" +
    "\uffbf\013\uffbf\014\uffbf\015\uffbf\016\uffbf\017\uffbf\022\uffbf" +
    "\023\uffbf\026\uffbf\031\uffbf\065\207\001\002\000\004\055" +
    "\210\001\002\000\004\031\211\001\002\000\004\062\212" +
    "\001\002\000\004\031\213\001\002\000\004\063\214\001" +
    "\002\000\004\064\215\001\002\000\004\065\216\001\002" +
    "\000\004\030\uffcb\001\002\000\004\024\ufff3\001\002\000" +
    "\004\024\ufff4\001\002\000\020\004\ufff1\005\ufff1\025\ufff1" +
    "\035\ufff1\037\ufff1\040\ufff1\045\ufff1\001\002\000\020\004" +
    "\047\005\062\025\226\035\056\037\232\040\224\045\050" +
    "\001\002\000\020\004\uffef\005\uffef\025\uffef\035\uffef\037" +
    "\uffef\040\uffef\045\uffef\001\002\000\014\004\047\005\062" +
    "\035\262\042\265\045\050\001\002\000\004\064\236\001" +
    "\002\000\020\004\ufff5\005\ufff5\025\ufff5\035\ufff5\037\ufff5" +
    "\040\ufff5\045\ufff5\001\002\000\004\035\234\001\002\000" +
    "\020\004\ufff0\005\ufff0\025\ufff0\035\ufff0\037\ufff0\040\ufff0" +
    "\045\ufff0\001\002\000\020\004\uffee\005\uffee\025\uffee\035" +
    "\uffee\037\uffee\040\uffee\045\uffee\001\002\000\004\035\233" +
    "\001\002\000\010\024\ufff2\066\016\067\017\001\002\000" +
    "\004\030\235\001\002\000\032\004\uffed\005\uffed\024\uffed" +
    "\025\uffed\035\uffed\037\uffed\040\uffed\045\uffed\046\uffed\050" +
    "\uffed\051\uffed\055\uffed\001\002\000\014\004\047\005\062" +
    "\035\056\045\050\065\uffdf\001\002\000\006\032\257\065" +
    "\uffe0\001\002\000\004\035\256\001\002\000\004\065\242" +
    "\001\002\000\004\024\243\001\002\000\024\004\uffe9\005" +
    "\uffe9\024\uffe9\035\uffe9\045\uffe9\046\uffe9\050\uffe9\051\uffe9" +
    "\055\uffe9\001\002\000\004\025\255\001\002\000\024\004" +
    "\047\005\062\024\041\035\247\045\050\046\043\050\042" +
    "\051\037\055\035\001\002\000\022\024\041\025\uffe1\035" +
    "\034\044\252\046\043\050\042\051\037\055\035\001\002" +
    "\000\012\020\uffcd\026\176\031\uffc9\035\uffd8\001\002\000" +
    "\024\004\uffe8\005\uffe8\024\uffe8\035\uffe8\045\uffe8\046\uffe8" +
    "\050\uffe8\051\uffe8\055\uffe8\001\002\000\004\025\uffe3\001" +
    "\002\000\032\004\047\005\062\021\061\033\045\034\063" +
    "\035\056\045\050\051\060\052\052\053\054\054\051\064" +
    "\055\001\002\000\040\006\067\007\101\010\072\011\100" +
    "\012\074\013\071\014\073\015\077\016\103\017\070\022" +
    "\102\023\065\026\075\030\254\031\066\001\002\000\004" +
    "\025\uffe2\001\002\000\020\004\uffec\005\uffec\025\uffec\035" +
    "\uffec\037\uffec\040\uffec\045\uffec\001\002\000\006\032\uffde" +
    "\065\uffde\001\002\000\012\004\047\005\062\035\056\045" +
    "\050\001\002\000\004\035\261\001\002\000\006\032\uffdd" +
    "\065\uffdd\001\002\000\006\035\uffd8\064\uffeb\001\002\000" +
    "\004\035\266\001\002\000\004\035\uffe5\001\002\000\004" +
    "\035\uffe4\001\002\000\004\064\uffea\001\002\000\006\030" +
    "\ufffa\031\ufffa\001\002\000\006\030\ufff7\031\271\001\002" +
    "\000\006\010\275\035\274\001\002\000\004\030\273\001" +
    "\002\000\006\036\ufffb\037\ufffb\001\002\000\006\030\ufff9" +
    "\031\ufff9\001\002\000\004\030\ufff8\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\274\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\007\005\006\001\001\000\004\007\267" +
    "\001\001\000\002\001\001\000\006\010\012\011\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\026" +
    "\037\031\035\001\001\000\004\036\174\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\016\143\026\144\031\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\025\056\032\052\033" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\035\075\001\001\000\002\001\001\000\010" +
    "\025\056\032\116\033\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\056\032\063" +
    "\033\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\075\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\025\056\032\104\033\045\001\001\000\010\025\056\032" +
    "\103\033\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\075\001\001\000\004\035\075\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\025" +
    "\056\032\111\033\045\034\112\001\001\000\004\035\075" +
    "\001\001\000\002\001\001\000\010\025\056\032\115\033" +
    "\045\001\001\000\002\001\001\000\004\035\075\001\001" +
    "\000\004\035\075\001\001\000\002\001\001\000\006\026" +
    "\121\031\035\001\001\000\004\027\123\001\001\000\006" +
    "\026\124\031\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\025\056" +
    "\032\111\033\045\034\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\056\032\133\033\045\001\001" +
    "\000\004\035\075\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\025\056\032\140\033\045" +
    "\001\001\000\004\035\075\001\001\000\006\026\142\031" +
    "\035\001\001\000\002\001\001\000\006\026\146\031\035" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\025\056\032\111\033\045\034" +
    "\154\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\025\056\032\171\033\045\001\001\000\004\035\075" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\025\056\032\176\033\045\001\001\000\004" +
    "\035\075\001\001\000\002\001\001\000\012\025\056\030" +
    "\203\032\201\033\045\001\001\000\004\035\075\001\001" +
    "\000\010\025\205\032\116\033\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\221\001\001\000\014\011\230\014\227\017\222\025\226" +
    "\037\224\001\001\000\002\001\001\000\006\020\262\025" +
    "\263\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\023\240\024\236\025\237\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\015\244\021\243\001\001\000\002\001" +
    "\001\000\014\014\247\016\245\025\226\026\144\031\035" +
    "\001\001\000\010\022\250\026\146\031\035\001\001\000" +
    "\004\036\174\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\025\056\032\252\033\045\001\001\000\004\035" +
    "\075\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\025\257\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\271\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
Scanner scanner;
	
	public parser(java.io.Reader input){
	scanner = new Scanner(input);
	}



	public String errores(int sys)
{
	if (sys == 3)
		return("TSTRING");
	else if (sys == 6)
		return("MULT");
	else if (sys == 5)
		return("RESTA");
	else if (sys == 45)
		return("PRINTLN");
	else if (sys == 44)
		return("OUT");
	else if (sys == 31)
		return("STATIC");
	else if (sys == 17)
		return("AND");
	else if (sys == 11)
		return("MEN_IG");
	else if (sys == 53)
		return("IMPLEM");
	else if (sys == 48)
		return("IN");
	else if (sys == 16)
		return("OR");
	else if (sys == 35)
		return("BOOL");
	else if (sys == 29)
		return("CLASS");
	else if (sys == 50)
		return("PARENTI");
	else if (sys == 7)
		return("DIV");
	else if (sys == 25)
		return("NUM");
	else if (sys == 4)
		return("SUMA");
	else if (sys == 47)
		return("EXIT");
	else if (sys == 36)
		return("IF");
	else if (sys == 33)
		return("MAIN");
	else if (sys == 51)
		return("PARENTD");
	else if (sys == 39)
		return("THIS");
	else if (sys == 27)
		return("ID");
	else if (sys == 22)
		return("PYCOMA");
	else if (sys == 43)
		return("SYSTEM");
	else if (sys == 34)
		return("RETURN");
	else if (sys == 40)
		return("TRUE");
	else if (sys == 42)
		return("NEW");
	else if (sys == 24)
		return("COMA");
	else if (sys == 8)
		return("DIF");	
	else if (sys == 20)
		return("CORCHI");
	else if (sys == 9)
		return("IG_IG");
	else if (sys == 32)
		return("VOID");
	else if (sys == 21)
		return("CORCHD");
	else if (sys == 28)
		return("IMPORT");
	else if (sys == 2)
		return("TINT");
	else if (sys == 15)
		return("NEG");
	else if (sys == 37)
		return("ELSE");
	else if (sys == 23)
		return("PUNTO");
	else if (sys == 49)
		return("READ");
	else if (sys == 10)
		return("MEN");
	else if (sys == 38)
		return("WHILE");
	else if (sys == 30)
		return("PUBLIC");
	else if (sys == 52)
		return("EXTENDS");
	else if (sys == 14)
		return("ASIGN");
	else if (sys == 26)
		return("STRING_CONS");
	else if (sys == 18)
		return("LLAVEI");
	else if (sys == 41)
		return("FALSE");
	else if (sys == 12)
		return("MAY_IG");
	else if (sys == 19)
		return("LLAVED");
	else if (sys == 13)
		return("MAY");
	else if (sys == 46)
		return("LENGTH");
	else
		return("error");
}
public void syntax_error(Symbol cur_token)
{
	if (cur_token.sym == 3)
		report_error("No se esperaba un 'String'", cur_token);
	else if (cur_token.sym == 6)
		report_error("No se esperaba un '*'", cur_token);
	else if (cur_token.sym == 5)
		report_error("No se esperaba un '-'", cur_token);
	else if (cur_token.sym == 45)
		report_error("No se esperaba un 'println'", cur_token);
	else if (cur_token.sym == 44)
		report_error("No se esperaba un 'out'", cur_token);
	else if (cur_token.sym == 31)
		report_error("No se esperaba un 'static'", cur_token);
	else if (cur_token.sym == 17)
		report_error("No se esperaba un '&&'", cur_token);
	else if (cur_token.sym == 11)
		report_error("No se esperaba un '<='", cur_token);
	else if (cur_token.sym == 53)
		report_error("No se esperaba un 'implements'", cur_token);
	else if (cur_token.sym == 48)
		report_error("No se esperaba un 'in'", cur_token);
	else if (cur_token.sym == 16)
		report_error("No se esperaba un '||'", cur_token);
	else if (cur_token.sym == 35)
		report_error("No se esperaba un 'boolean'", cur_token);
	else if (cur_token.sym == 29)
		report_error("No se esperaba un 'class'", cur_token);
	else if (cur_token.sym == 50)
		report_error("No se esperaba un '('", cur_token);
	else if (cur_token.sym == 7)
		report_error("No se esperaba un '/'", cur_token);
	else if (cur_token.sym == 25)
		report_error("No se esperaba un valor numérico", cur_token);
	else if (cur_token.sym == 4)
		report_error("No se esperaba un '+'", cur_token);
	else if (cur_token.sym == 47)
		report_error("No se esperaba un 'exit'", cur_token);
	else if (cur_token.sym == 36)
		report_error("No se esperaba un 'if'", cur_token);
	else if (cur_token.sym == 33)
		report_error("No se esperaba un 'main'", cur_token);
	else if (cur_token.sym == 51)
		report_error("No se esperaba un ')'", cur_token);
	else if (cur_token.sym == 39)
		report_error("No se esperaba un 'this'", cur_token);
	else if (cur_token.sym == 27)
		report_error("No se esperaba un identificador", cur_token);
	else if (cur_token.sym == 22)
		report_error("No se esperaba un ';'", cur_token);
	else if (cur_token.sym == 43)
		report_error("No se esperaba un 'system'", cur_token);
	else if (cur_token.sym == 34)
		report_error("No se esperaba un 'return'", cur_token);
	else if (cur_token.sym == 40)
		report_error("No se esperaba un 'true'", cur_token);
	else if (cur_token.sym == 42)
		report_error("No se esperaba un 'new'", cur_token);
	else if (cur_token.sym == 24)
		report_error("No se esperaba un ','", cur_token);
	else if (cur_token.sym == 8)
		report_error("No se esperaba un '!='", cur_token);
	else if (cur_token.sym == 20)
		report_error("No se esperaba un '['", cur_token);
	else if (cur_token.sym == 9)
		report_error("No se esperaba un '=='", cur_token);
	else if (cur_token.sym == 32)
		report_error("No se esperaba un 'void'", cur_token);
	else if (cur_token.sym == 21)
		report_error("No se esperaba un ']'", cur_token);
	else if (cur_token.sym == 28)
		report_error("No se esperaba un 'import'", cur_token);
	else if (cur_token.sym == 2)
		report_error("No se esperaba un 'int'", cur_token);
	else if (cur_token.sym == 15)
		report_error("No se esperaba un '!'", cur_token);
	else if (cur_token.sym == 37)
		report_error("No se esperaba un 'else'", cur_token);
	else if (cur_token.sym == 23)
		report_error("No se esperaba un '.'", cur_token);
	else if (cur_token.sym == 49)
		report_error("No se esperaba un 'read'", cur_token);
	else if (cur_token.sym == 10)
		report_error("No se esperaba un '<'", cur_token);
	else if (cur_token.sym == 38)
		report_error("No se esperaba un 'while'", cur_token);
	else if (cur_token.sym == 30)
		report_error("No se esperaba un 'public'", cur_token);
	else if (cur_token.sym == 52)
		report_error("No se esperaba un 'extends'", cur_token);
	else if (cur_token.sym == 14)
		report_error("No se esperaba un '='", cur_token);
	else if (cur_token.sym == 26)
		report_error("No se esperaba una cadena de texto", cur_token);
	else if (cur_token.sym == 18)
		report_error("No se esperaba un '{'", cur_token);
	else if (cur_token.sym == 41)
		report_error("No se esperaba un 'false'", cur_token);
	else if (cur_token.sym == 12)
		report_error("No se esperaba un '>='", cur_token);
	else if (cur_token.sym == 19)
		report_error("No se esperaba un '}'", cur_token);
	else if (cur_token.sym == 13)
		report_error("No se esperaba un '>'", cur_token);
	else if (cur_token.sym == 46)
		report_error("No se esperaba un 'length'", cur_token);	
	else 
		report_error("error", cur_token);}
 public void report_error(String message, Object info) {
   StringBuffer m = new StringBuffer("Error ");

   if (info instanceof java_cup.runtime.Symbol) {
     m.append( "(" + errores(((java_cup.runtime.Symbol)info).sym) +")" );
     m.append(" en fila "+ ((java_cup.runtime.Symbol)info).left + " columna " + ((java_cup.runtime.Symbol)info).right );
     
     if (((java_cup.runtime.Symbol)info).value != null)
       m.append(". Lexema: " + ((java_cup.runtime.Symbol)info).value.toString());
     
   }
   m.append(" : "+message);
   
   System.out.println(m);
 }

	public void report_fatal_error(String message, Object info) {
		report_error(message, info);
		throw new RuntimeException("Error Fatal de Sintáxis");
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // op ::= AND 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // op ::= OR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // op ::= MAY 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // op ::= MAY_IG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // op ::= MEN_IG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // op ::= MEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // op ::= IG_IG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // op ::= DIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // op ::= DIV 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // op ::= MULT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // op ::= RESTA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // op ::= SUMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // explist ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // explist ::= explist COMA exp 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // explist ::= exp 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expsimpl ::= STRING_CONS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expsimpl ::= PARENTI exp PARENTD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expsimpl ::= NEG exp 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expsimpl ::= NEW ID PARENTI explist PARENTD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expsimpl ::= NEW TINT CORCHI exp CORCHD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expsimpl ::= type 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expsimpl ::= THIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expsimpl ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expsimpl ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expsimpl ::= NUM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= exp PUNTO ID PARENTI explist PARENTD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // exp ::= exp PUNTO LENGTH 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // exp ::= exp CORCHI exp CORCHD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // exp ::= exp op exp 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // exp ::= expsimpl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // thisaux ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("thisaux",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // thisaux ::= THIS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("thisaux",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // systemaux ::= PARENTI type PARENTD SYSTEM PUNTO IN PUNTO READ PARENTI PARENTD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("systemaux",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // systemaux ::= exp 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("systemaux",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // idaux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idaux",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // idaux ::= CORCHI exp CORCHD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idaux",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ifaux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ifaux",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ifaux ::= ELSE statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ifaux",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // statement ::= thisaux PUNTO ID PARENTI explist PARENTD PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // statement ::= ID idaux ASIGN systemaux PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // statement ::= SYSTEM PUNTO EXIT PARENTI NUM PARENTD PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // statement ::= SYSTEM PUNTO OUT PUNTO PRINTLN PARENTI exp PARENTD PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // statement ::= WHILE PARENTI exp PARENTD statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // statement ::= IF PARENTI exp PARENTD statement ifaux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // statement ::= LLAVEI variasstatement LLAVED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // type ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // type ::= TSTRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // type ::= TINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // type ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // type ::= TINT CORCHI CORCHD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // formallistaux ::= formallistaux COMA type ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallistaux",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // formallistaux ::= type ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallistaux",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // formallist ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallist",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // formallist ::= formallistaux 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallist",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // methoddeclauxdos ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxdos",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // methoddeclauxdos ::= RETURN exp PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxdos",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // methoddeclauxuno ::= variasvardecl variasstatement methoddeclauxdos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxuno",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // methoddeclaux ::= VOID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclaux",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // methoddeclaux ::= type 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclaux",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // variasstatement ::= variasstatement statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasstatement",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // variasstatement ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasstatement",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // variasvardecl ::= variasvardecl vardecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasvardecl",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // variasvardecl ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasvardecl",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // constrdeclormethoddecl ::= PUBLIC methoddeclaux ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("constrdeclormethoddecl",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // constrdeclormethoddecl ::= PUBLIC ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("constrdeclormethoddecl",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // methoddecl ::= constrdeclormethoddecl PARENTI formallist PARENTD LLAVEI methoddeclauxuno LLAVED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddecl",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // vardecl ::= type ID PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vardecl",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bodydecl ::= bodydecl classdecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // bodydecl ::= bodydecl methoddecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // bodydecl ::= bodydecl vardecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bodydecl ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // classdeclaux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // classdeclaux ::= IMPLEM ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // classdeclaux ::= EXTENDS ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // classdecl ::= CLASS ID classdeclaux LLAVEI bodydecl LLAVED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // mainclass ::= CLASS ID LLAVEI PUBLIC STATIC VOID MAIN PARENTI TSTRING CORCHI CORCHD ID PARENTD LLAVEI statement LLAVED LLAVED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("mainclass",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-16)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // importdeclaux ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdeclaux",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // importdeclaux ::= PUNTO MULT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdeclaux",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // typename ::= typename PUNTO ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("typename",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // typename ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("typename",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // importdecl ::= IMPORT typename importdeclaux PYCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdecl",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // variasclassdecl ::= variasclassdecl classdecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasclassdecl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // variasclassdecl ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasclassdecl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // variasimportdecl ::= variasimportdecl importdecl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasimportdecl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // variasimportdecl ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasimportdecl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= variasimportdecl variasclassdecl mainclass 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

