
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 13 18:00:17 CST 2013
//----------------------------------------------------

package compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 3;
  public static final int MULT = 6;
  public static final int RESTA = 5;
  public static final int STRING_CONS = 26;
  public static final int PRINTLN = 45;
  public static final int OUT = 44;
  public static final int STATIC = 31;
  public static final int AND = 17;
  public static final int MEN_IG = 11;
  public static final int IMPLEM = 53;
  public static final int IN = 48;
  public static final int OR = 16;
  public static final int BOOL = 35;
  public static final int CLASS = 29;
  public static final int PARENTI = 50;
  public static final int DIV = 7;
  public static final int NUM = 25;
  public static final int SUMA = 4;
  public static final int EXIT = 47;
  public static final int IF = 36;
  public static final int MAIN = 33;
  public static final int PARENTD = 51;
  public static final int THIS = 39;
  public static final int ID = 27;
  public static final int PYCOMA = 22;
  public static final int EOF = 0;
  public static final int SYSTEM = 43;
  public static final int RETURN = 34;
  public static final int TRUE = 40;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int DIF = 8;
  public static final int CORCHI = 20;
  public static final int IG_IG = 9;
  public static final int VOID = 32;
  public static final int CORCHD = 21;
  public static final int IMPORT = 28;
  public static final int TINT = 2;
  public static final int NEG = 15;
  public static final int ELSE = 37;
  public static final int PUNTO = 23;
  public static final int READ = 49;
  public static final int MEN = 10;
  public static final int WHILE = 38;
  public static final int PUBLIC = 30;
  public static final int EXTENDS = 52;
  public static final int ASIGN = 14;
  public static final int LLAVEI = 18;
  public static final int FALSE = 41;
  public static final int MAY_IG = 12;
  public static final int LLAVED = 19;
  public static final int MAY = 13;
  public static final int LENGTH = 46;
}

